### PR TITLE
lib: option to allow any file

### PR DESCRIPTION
**Pull request by LinusU**
Allows the receiving of files regardless of their fieldname.

I'm still not sure if we should merge this. @jpfluger, @hacksparrow, what are your thoughts?

### CODE REVIEW

**Comment by imZack** [comment]
Needs this feature :+1:

**Comment by mjhasbach** [comment]
+1

**Comment by no-donut-for-you** [comment]
+1

**Comment by JedWatson** [comment]
I think this is a valuable addition; there are cases in dynamic systems (e.g. CMS) where the field configuration can't be known before a form is submitted, especially when developing a generic API endpoint that may handle updating different types of objects, as per the GraphQL use case.

It seems like the explicit field naming was introduced as a best practice / security feature (?) but for some cases an explicit opt-in to dynamically detect & accept any file fields would be useful.

**Comment by JedWatson** [comment]
@LinusU @jpfluger @hacksparrow any chance we can get an indication of whether this will be merged / implemented? otherwise I'll start working on an alternate solution.

**Comment by LinusU** [comment]
I could probably merge it for you tonight (Swedish time) :cake:

**Comment by jpfluger** [comment]
@LinusU, I'm good with this addition. I also appreciate the **warning** in the readme.

**Comment by hacksparrow** [comment]
👍

**Comment by JedWatson** [comment]
Thanks :100:

**Comment by LinusU** [comment]
Released as `1.1.0` :shipit: :100:

**Pull request merged**
