### PR TITLE
storage: replace deprecated pseudoRandomBytes with randomBytes

### PR DESCRIPTION
**Pull request by gireeshpunathil**
Fixes: https://github.com/expressjs/multer/issues/509
Fixes: https://github.com/expressjs/multer/issues/811

cc @LinusU

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
bump. Is there anything I can help with, to move this forward? two issues waiting on this. thanks!

**Comment by geoynomous** [comment]
it might be delayed, as older versions of node do not have that function?

**Comment by gireeshpunathil** [comment]
that depends; on :
 - which version of multer this is going to be cut into
 - which version of node `that` version multer is going to support

**Comment by LinusU** [comment]
Sorry for not getting to this!

`crypto.randomBytes` is supported on Node.js 0.10 which is what Multer 1.x is supporting, so there should be no problem merging this 👍

**Comment by geoynomous** [comment]
Is there also a 2.0 release coming?

**Pull request merged**
