### PR TITLE
#790 bump busboy up to solve encoding bug

### PR DESCRIPTION
**Pull request by erano067**
busboy in package json version(^0.2.11 = 0.2.14) does not handle multi fields in content-disposition.
so i bump up the version and fix all minor api breaking changes of busboy.

### CODE REVIEW

**Comment by justinnitz** [comment]
A CVE is now associated with the dicer package. Upgrading to at least 1.0.0 of busboy removes dicer from multer's transitive dependency list. 

https://github.com/mscdex/busboy/issues/250 
https://security.snyk.io/vuln/SNYK-JS-DICER-2311764

**Comment by mrded** [comment]
Two problems here:

1. The change is not formated: do `./node_modules/.bin/standard --fix`
2. The tests are failing: `npm run test` 
 - `Error Handling: should report errors from busboy parsing`
 -  `Unicode: 2) should handle unicode filenames`

**Comment by mrded** [comment]
Two problems here:

1. The change is not formated: do `./node_modules/.bin/standard --fix`
2. The tests are failing: `npm run test` 
 - `Error Handling: should report errors from busboy parsing`
 -  `Unicode: 2) should handle unicode filenames`

**Comment by progsmile** [comment]
> Two problems here
I've run format command on different node versions (8, 10, 12, 14, 16, 18) - it's ok.
Tests are failing on nodes: `v8.17.0`, `v9.11.2`, Instant error because of `catch` without error parameter.
Starting from node `v10.24.1` tests are ok from my local pc.

I see node.js 6 - is not fittable any more, because `standard` requires  node `>=8.10`. And travis.ci has many old versions.
What is requirement for node.js version?

**Comment by progsmile** [comment]
> Two problems here:

What the version of node.js?

**Comment by RopoMen** [comment]
@mrded unicode issue solution is in this PR https://github.com/expressjs/multer/pull/1102

**Comment by LinusU** [comment]
This is done and discussed in #1097, currently it's published as `1.4.5-lts.1`

**Pull request closed without merging**
