### PR TITLE
Fixed inconsistent naming

### PR DESCRIPTION
**Pull request by NikxDa**
Named variables javascript-like.

### CODE REVIEW

**Comment by NikxDa** [comment]
Hope the checks pass now.

**Comment by NikxDa** [comment]
Finally fixed my inability to rename variables correctly. m(

**Comment by LinusU** [comment]
This needs a major semver bump since it will be backwards incompatible. Could you squash everything into one commit and also update the `README.md` file?

**Comment by NikxDa** [comment]
Hey, I added the updated README. How to squash all the commits into one new? I tried, but it doesn't seem to work as you want it.

**Comment by LinusU** [comment]
@NikxDa could you check out #399 and see if everything is named correctly there? In that case this is already a part of the alpha release of 2.x 🎉

**Comment by NikxDa** [comment]
I have not had a lot of time to check, but it looks good! Thanks for remembering it 👍

**Pull request closed without merging**
