### PR TITLE
add chinese language readme.md

### PR DESCRIPTION
**Pull request by zengming00**
add chinese language readme.md, to let chinese better use this project , tks

### CODE REVIEW

**Comment by LinusU** [comment]
Thank you for this, it is awesome. The only concern I have is how we will keep this up to date 💭 

I would like to bring this up with the Express TC and see what the thoughts are...

**Comment by jpfluger** [comment]
Nice job @zengming00! :+1:  Keeping the translation up-to-date is the issue, though. I do like @crandmck's observations in [Translated Readmes](https://github.com/expressjs/discussions/issues/38). Maybe...? 

* Place translations into a subfolder for translations
* Each translation gets a disclaimer at the top
* Each translation at the top displays the multer version to which the translation applies.

**Comment by zengming00** [comment]
@jpfluger good idea,  yes, keeping the translation up-to-date is the issue, and @crandmck is right , small differences in translation can completely change the meaning, and i'm non-English speakers, In this document, have some sentences real can't understand, I use myself experience and coding some demo to try it , so translate to other language it's not an easy thing. may be my translation can help some people.
How to keep this up to date , may be i can period update it , a week or a month , or other chinese people will be update it . tks

**Comment by crandmck** [comment]
> Each translation gets a disclaimer at the top
> Each translation at the top displays the multer version to which the translation applies.

@jpfluger Yes, I think these suggestions make a lot of sense.  As a convenience, I would also add the translation date (even though someone could figure that out from the git history).

So @zengming00 could you please add the following note **in Chinese** at the top of the page:

> This document was translated on 3 Oct 2016 for multer version 1.2.0. It may be outdated compared to the [English README](README.md). 

I don't know that the Chinese README needs to be in a separate folder...  Since the filename has the ISO lang code, that might be sufficient.  But I'll leave that decision to @LinusU and others.

**Comment by zengming00** [comment]
@crandmck updated

**Comment by crandmck** [comment]
LGTM.

**Comment by LinusU** [comment]
Awesome, thank you for this!

**Pull request merged**
