### PR TITLE
[WIP] Breaking changes

### PR DESCRIPTION
**Pull request by LinusU**
I have now updated the README.md to a state which I think is quite good. I've tried to scale back and simplify as much as possible.

My intentions is to try and have a discussion here on how the api for the next breaking change should look like.

What I've changed:

- Removed `includeEmptyFields`, this will follow the W3C JSON form spec
- Removed `putSingleFilesInArray`, as discussed before this is now always true
- Removed `rename`, `changeDest` and `inMemory` in favour of `storage`, discussion in #126, #123 
- Removed `onFileUploadStart`, `onFileUploadData` and `onFileUploadEnd` in favour of `storage`
- Made some slight changes to the `File` properties, discussion in #130 
- Removed the rest of the `on*` in favour of `next(err)`, discussion in #128 

Todo:

- [x] It's no longer possible to skip files, maybe have a `filesFilter` option that's a function `(req, file, cb)`
- [x] Document the API for people who want to implement their own Storage Engine

This isn't implemented yet and I'm not saying that this is they way it's going to be, it's an early draft to a proposal. Comments very welcome :)

[Read the new README.md](https://github.com/expressjs/multer/blob/4c4cb61d417cadbcbf5ebfb7e2b1463c9af6e757/README.md)

### CODE REVIEW

**Comment by LinusU** [comment]
I've now added a commit to check the coding style with [feross/standard](https://github.com/feross/standard), I have slowly been converting to this since it follows very closely to the styling guide that @jpfluger directed me to.

It will check the style every time you run `npm test`, so hopefully we should never need to nitpick styling issues in our pull requests ever again :beers:

**Comment by LinusU** [comment]
Just pushed some much faster tests! See #132 for discussion

**Comment by jpfluger** [comment]
@LinusU: very clear abstractions. Well done!  `index.js` is easily readable. I love how you split up `disk.js` and `memory.js`. That should give enough room to attach other storage modules. I'll spend this weekend integrating `breaking-changes` into one of my projects. This will help me digest more of your work. Thank you!

**Comment by LinusU** [comment]
Thank you for your kind words! I really felt that the code improved substantially :)

One thing to watch out for currently is that the field-parsing is horribly broken. It just stores simple key-value pairs currently, so `array[]=1&array[]=2` will be parsed as `{ 'array[]': [1,2] }` instead of `{ array: [1,2] }`.

Updated TODO:
- [ ] Create `StorageEngine.md`
- [ ] Implement `fileFilter: function (req, file, cb) { ... }`
- [ ] Make `append-filed(store, key, val)` W3C JSON form spec compliant

**Comment by LinusU** [comment]
Just implemented the `fileFilter` option :)

**Comment by LinusU** [comment]
Just pushed some better error handling, tests for error handling and a workaround for mscdex/busboy#6.

It's now also possible to see which field triggered the errors. This can be used by the end user to display errors like "The profile image was too large" or "The description was too long".

**Comment by jpfluger** [comment]
Excellent. Mocha tests ran well locally.

**Comment by LinusU** [comment]
The field parser is now using [LinusU/node-append-field](https://github.com/LinusU/node-append-field) which I just wrote. It makes it both incremental and W3C HTML JSON form spec compliant.

**Comment by LinusU** [comment]
I have now documented how to implement a storage engine and linked it form the main readme.

I think that the only thing that I'm thinking about now is #133.

**Comment by LinusU** [comment]
I had forgotten to add the new source files to the package.json `files` array, which resulted in the package not working when installed thru npm.

Just pushed a fix to that and I'm now using this version of `multer` in a larger project by adding this to my package.json dependencies: `"multer": "expressjs/multer#b32ac18"`

**Comment by LinusU** [comment]
`req.files` is now an array instead of an object, see the discussion in #133

**Comment by LinusU** [comment]
Anyone interested in taking the latest changes for a spin can use the following in their `package.json` `dependencies`:

    "multer": "expressjs/multer#6ef893b"

**Comment by LinusU** [comment]
Ping @hacksparrow @jpfluger 

I'm feeling quite satisfied with the progress and I can't think of anything more to change at the moment. Would you guys possibly have some time to look at the code and, maybe most important, look at the new api and tell me what you think.

It would be great if we could find one or two people using `multer` on a larger scale that could test to switch to this new version and see what they think. I do believe that many of the bugs that are currently open will be solved by this and also a lot of confusion from `onFileUploadComplete` and `onParseEnd` will be mitigated.

Cheers :beers:

**Comment by hacksparrow** [comment]
Good job! I am a little occupied currently, will review it coming weekend and update. 🍻

**Comment by hacksparrow** [comment]
Looking good. @jpfluger do you want to take a look as well? Also, does it include / address the breaking-changes improvements you had on your mind? If we are all covered, I think it's time to update the version and publish on npm.

**Comment by jpfluger** [comment]
I'll test the items you speak of on Monday. When LinusU made his initial posts, I quickly cloned and ran general tests. Everything passed. I am impressed how how he opened multer up to use other storage types, revamped fields to use W3C JSON specs and quickened mocha tests. It's great to have a fresh mind give new perspective to the project!

**Comment by jpfluger** [comment]
Please see my comments in #133. 

Still testing a few other things. Give me another day on this.

**Comment by jpfluger** [comment]
Ok, I've finished testing. Here's my 2-cent observations.

* Overall - improved architecture: storage types, W3C JSON, faster mocha, streamlined error handling.
* Re. error handling. Is there a suggested way to handle errors from w/in the new multer?  This might want to be documented. The new multer shifts error-handling to the `next` middleware handler. Context: some users actively monitor all errors and do something with them (eg server reports or respond back via socket.io or delete uploaded and erred files).
* I think `res` should be included as a param for `fileFilter` and `storage.handleFile`. This allows `res.locals` to be accessed for individual needs and whatever else a user finds useful with the `res` object.
* Re. `req.files` as an array of files versus an object key that points to an array of files. My thoughts on this are in #133. @hacksparrow should weight-in.
* Re. security. `fileFilter` improves security and will close #59. If the user implements their own fileFilter, they won't get unsolicited file uploads. Probably be a good idea to write up a document w/ best security practices. I can do this.

@LinusU has done a lot of great work!

**Comment by LinusU** [comment]
We should add something to the Readme regarding error handling. Basically this just hands off any errors to express, but since it didn't before, it might be a good idea to write that down.

- [ ] Add info about error handling to Readme

What I don't like about passing `res` to user provided functions is that the main purpose of `res` is to respond to the client, yet we depend on that not happening yet. I feel that if we provide `res` we also need to provide `abort` and the user needs to call that whenever they have decided to respond to the request themselves. Or we could try and detect that automatically, but either way I feel that this complicates things a bit too much.

Another thing from #59 is that I don't think that we should ever encourage adding multer as a middleware to the entire application. It should be added in front of the route that will handle the file/files.

Maybe we could take these ideas and put them together to something like this? Or maybe this would add unnecessary complex for the user. The upside would be no more global file upload handlers, I guess that this would pretty much solve #59? (ping @james147)

```javascript
var app = express()
var upload = multer({ ... })

app.post('/profile', upload.single('avatar'), function (req, res, next) {
  // req.file is the `avatar` file
})

app.post('/photos/upload', upload.array('photos'), function (req, res, next) {
  // req.files is array of `photos` files
})

app.post('/upload', upload.any(), function (req, res, next) {
  // req.files is an object (String -> Array) where fieldname is the key, and the value is array of files
})
```

**Comment by jpfluger** [comment]
I am fine with no more global file upload handlers. I'm elated that security is a first-class passenger.

Re #59. Placing multer on the actual route and doing filename checks is most of the issue, thanks to `fileFilter`. But `fileFilter` still needs to know the count of file.fieldNames to complete #59.  Unfortunately, like I mentioned in #133 I got it to work for my needs by only using `res.locals` to track checked file.fieldNames and corresponding file counts. Maybe in place of `res` as a parameter to `fileFilter`, add the current count of uploaded files for file.fieldName. This might be the simplest, allowing me to replicate what I did in #133 but get rid of `res` as a parameter.  Do you see any downsides to that approach?

Re. use of `res` as a parameter. I am okay with not having `res` as a parameter, esp b/c of how `abort` operates. 

Would you implement your suggestions in breaking-changes?

**Comment by jpfluger** [comment]
Re. error-handling using `next(err)`. I'm okay with it, so long as my request is ajax. If the request is non-ajax, I think I'd prefer means to allow the route handler to know there was an abortable error in multer and render the page with an alert box next to the file input. What about having an option called `option.noNextErr`, which adds the err to req (eg `req.errMulter = err`, then calls next()?

**Comment by LinusU** [comment]
Pushed improved documentation. Starting work on error handling now :)

**Comment by hacksparrow** [comment]
Excellent!

**Comment by jpfluger** [comment]
I added an [ErrorHandling doc](https://github.com/expressjs/multer/blob/breaking-changes/ErrorHandling.md) that gives an example for manual mode.

This version is working great in one of my projects! I think @hacksparrow should take a look. He may find something else to clean up and will need to progress versions anyway. In my opinion, it's ready to go!  Well done @LinusU...  :100:

**Comment by dustin-H** [comment]
Just worked at [multer-storage-pkgcloud](https://github.com/dustin-H/multer-storage-pkgcloud). Love the new Multer usage (single/array/fields) and flexibility through custom storages! 

Great Job @LinusU !

**Comment by LinusU** [comment]
Thank you! :ok_hand:

**Pull request merged**
