### PR TITLE
[WIP] test: express integration

### PR DESCRIPTION
**Pull request by LinusU**
Trying to track down the bug in #168

To run tests from this branch:
```sh
git clone https://github.com/expressjs/multer.git
cd multer
git checkout express-integration-test
npm install
npm test
```

### CODE REVIEW

**Comment by LinusU** [comment]
Okay so I actually managed to get the test to fail. Turns out that it only happens when the file is large enough to get chunked up, and I had to actually wait for the `finish` event on the request to see that it failed.

I still don't know how to fix it thought :confused: I thought it would be to add `req.resume()` in `done`, but it apparently wasn't that easy...

**Comment by vmartis** [comment]
Hi,

test fails in my environment:


  Disk Storage
    1) should process parser/form-data POST request
    √ should process empty fields and an empty file
    2) should process multiple files
    √ should remove uploaded files on error
    √ should report error when directory doesn't exist

  Error Handling
    √ should respect parts limit
    √ should respect file size limit
    √ should respect file count limit
    √ should respect file key limit
    √ should respect field key limit
    √ should respect field value limit
    √ should respect field count limit
    √ should respect fields given
    √ should report errors from storage engines

  Expected files
    √ should reject single unexpected file
    √ should reject array of multiple files
    √ should reject overflowing arrays
    √ should accept files with expected fieldname
    √ should reject files with unexpected fieldname

  Express Integration
    3) should work with express error handling

  Fields
    √ should process multiple fields
    √ should process empty fields
    √ should not process non-multipart POST request
    √ should not process non-multipart GET request
    √ should handle basic keys
    √ should handle multiple values
    √ should handle deeper structure
    √ should handle sparse arrays
    √ should handle even deeper
    √ should handle such deep
    √ should handle merge behaviour
    √ should handle bad fields
    √ should convert arrays into objects

  File Filter
    √ should skip some files

  Functionality
    4) should upload the file to the `dest` dir
    √ should rename the uploaded file
    √ should ensure all req.files values (single-file per field) point to an array
    √ should ensure all req.files values (multi-files per field) point to an array
    5) should rename the destination directory to a different directory

  Memory Storage
    6) should process multipart/form-data POST request
    √ should process empty fields and an empty file
    7) should process multiple files

  Reuse Middleware
    8) should accept multiple requests

  Select Field
    √ should select the first file with fieldname
    √ should select all files with fieldname

  Unicode
    9) should handle unicode filenames


  37 passing (434ms)
  9 failing

  1) Disk Storage should process parser/form-data POST request:

      Uncaught AssertionError: 1803 == 1778
      + expected - actual

      -1803
      +1778

      at c:\tmp\mutler\multer\test\disk-storage.js:44:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at c:\tmp\mutler\multer\lib\make-middleware.js:141:11
      at WriteStream.<anonymous> (c:\tmp\mutler\multer\storage\disk.js:43:9)
      at finishMaybe (_stream_writable.js:484:14)
      at afterWrite (_stream_writable.js:362:3)
      at onwrite (_stream_writable.js:352:7)
      at WritableState.onwrite (_stream_writable.js:105:5)
      at fs.js:1799:5
      at FSReqWrap.strWrapper (fs.js:568:5)

  2) Disk Storage should process multiple files:

      Uncaught AssertionError: 128 == 122
      + expected - actual

      -128
      +122

      at c:\tmp\mutler\multer\test\disk-storage.js:120:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at Busboy.<anonymous> (c:\tmp\mutler\multer\lib\make-middleware.js:153:7)

  3) Express Integration should work with express error handling:
     Uncaught Error: read ECONNRESET
      at exports._errnoException (util.js:746:11)
      at TCP.onread (net.js:559:26)

  4) Functionality should upload the file to the `dest` dir:

      Uncaught AssertionError: 1803 == 1778
      + expected - actual

      -1803
      +1778

      at c:\tmp\mutler\multer\test\functionality.js:55:16
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at c:\tmp\mutler\multer\lib\make-middleware.js:141:11
      at WriteStream.<anonymous> (c:\tmp\mutler\multer\storage\disk.js:43:9)
      at finishMaybe (_stream_writable.js:484:14)
      at afterWrite (_stream_writable.js:362:3)
      at onwrite (_stream_writable.js:352:7)
      at WritableState.onwrite (_stream_writable.js:105:5)
      at fs.js:1799:5
      at FSReqWrap.strWrapper (fs.js:568:5)

  5) Functionality should rename the destination directory to a different directory:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at c:\tmp\mutler\multer\test\functionality.js:132:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at c:\tmp\mutler\multer\lib\make-middleware.js:141:11
      at WriteStream.<anonymous> (c:\tmp\mutler\multer\storage\disk.js:43:9)
      at finishMaybe (_stream_writable.js:484:14)
      at afterWrite (_stream_writable.js:362:3)
      at onwrite (_stream_writable.js:352:7)
      at WritableState.onwrite (_stream_writable.js:105:5)
      at fs.js:1799:5
      at FSReqWrap.strWrapper (fs.js:568:5)

  6) Memory Storage should process multipart/form-data POST request:

      Uncaught AssertionError: 1803 == 1778
      + expected - actual

      -1803
      +1778

      at c:\tmp\mutler\multer\test\memory-storage.js:31:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at Busboy.<anonymous> (c:\tmp\mutler\multer\lib\make-middleware.js:153:7)

  7) Memory Storage should process multiple files:

      Uncaught AssertionError: 128 == 122
      + expected - actual

      -128
      +122

      at c:\tmp\mutler\multer\test\memory-storage.js:107:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at Busboy.<anonymous> (c:\tmp\mutler\multer\lib\make-middleware.js:153:7)

  8) Reuse Middleware should accept multiple requests:

      Uncaught AssertionError: 1803 == 1778
      + expected - actual

      -1803
      +1778

      at c:\tmp\mutler\multer\test\reuse-middleware.js:40:18
      at Array.forEach (native)
      at c:\tmp\mutler\multer\test\reuse-middleware.js:37:19
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at Busboy.<anonymous> (c:\tmp\mutler\multer\lib\make-middleware.js:153:7)

  9) Unicode should handle unicode filenames:

      Uncaught AssertionError: 1803 == 1778
      + expected - actual

      -1803
      +1778

      at c:\tmp\mutler\multer\test\unicode.js:50:14
      at c:\tmp\mutler\multer\test\_util.js:26:7
      at done (c:\tmp\mutler\multer\lib\make-middleware.js:41:7)
      at indicateDone (c:\tmp\mutler\multer\lib\make-middleware.js:45:51)
      at c:\tmp\mutler\multer\lib\make-middleware.js:141:11
      at WriteStream.<anonymous> (c:\tmp\mutler\multer\storage\disk.js:43:9)
      at finishMaybe (_stream_writable.js:484:14)
      at afterWrite (_stream_writable.js:362:3)
      at onwrite (_stream_writable.js:352:7)
      at WritableState.onwrite (_stream_writable.js:105:5)
      at fs.js:1799:5
      at FSReqWrap.strWrapper (fs.js:568:5)



npm ERR! Test failed.  See above for more details.

**Comment by LinusU** [comment]
We're all good!

Debugging this was a pain! :bug: :gun:

**Comment by hacksparrow** [comment]
👏👍🏻

**Comment by LinusU** [comment]
I think that this actually was because of a bug in Node.js, and I just managed to work around it a bit. There is still problem thought as shown by #192.

See joyent/node#25823 :sob:

**Pull request merged**
